### ISSUE TITLE
typings could not identify it 

### ISSUE THREAD

**Issue by liangwang320** [suhdev/firebase-3-typescript#3]
it's great to have this. However, when I implemented into real project,typings simply could not identify/intellisense it.

code snippets:

///<reference path='./firebase.d.ts">

class MyTest {
    test() {
       firebase.database.ref();
   }
}

**Comment by suhdev** [comment]
Can you post the folder structure of your project, and also, post your tsconfig.json.

**Comment by RickCarlino** [comment]
@liangwang320 As a side note, you can share code snippets on GitHub by using three backticks (`).

**Comment by liangwang320** [comment]
I tried again today and found it works even without it. Intellisense works perfectly on angularfire2 itself.
see attached test example (don't forget  "npm install")

[test.zip](https://github.com/suhdev/firebase-3-typescript/files/329373/test.zip)

**Comment by suhdev** [comment]
I'm closing this issue then.
